export { Authorization } from './authorization/authorization'
export { Home } from './home/home'
export { Projects } from './projects/projects'
export { Dashboard } from './dashboard/dashboard'
export { Settings } from './settings/settings'
export { NotFound } from './not-found/not-found'
export { DefaultPage } from './default-page/default-page'