export {BiSearch as SearchIcon} from 'react-icons/bi'
export {BiLogOut as LogOutIcon} from 'react-icons/bi'
export {BiHomeAlt as HomeIcon} from 'react-icons/bi'
export {FiSettings as SettingsIcon} from 'react-icons/fi'
export {AiOutlineFolderOpen as ProjectsIcon} from 'react-icons/ai'
export { BiMoon as DarkThemeIcon} from 'react-icons/bi'
export { MdOutlineWbSunny as LightThemeIcon } from 'react-icons/md'

export {BiCheck as ToggleIcon} from 'react-icons/bi'
export {BiCheckDouble as ReadyToggleICon} from 'react-icons/bi'
export {BiTrashAlt as RemoveIcon} from 'react-icons/bi'
export {FaRegWindowClose as ClosedIcon} from 'react-icons/fa'
export {HiOutlineFolder as ProjectHomeIcon} from 'react-icons/hi'
export {FiList as ListIcon} from 'react-icons/fi'
export {RiFolderAddFill as AddFolderIcon} from 'react-icons/ri'

export {GoListUnordered as AllListIcon} from 'react-icons/go'
export {GoTasklist as ToggleListIcon} from 'react-icons/go'
export {MdDateRange as DateListIcon} from 'react-icons/md'
export {TbExternalLink as NavLinkIcon} from 'react-icons/tb'

export {AiFillFileAdd as AddProjectIcon} from 'react-icons/ai'
export {CgClose as ClosedFormIcon} from 'react-icons/cg'